/**
 * Created by lsw on 2018/12/30 0030.
 */
export const RECEIVE_SHOPS = 'receive_shops'
export const RECEIVE_CART_LIST = 'receive_cart_list'

export const RECEIVE_CURRENTCATEGORY = 'RECEIVE_CURRENTCATEGORY'

export const RECEIVE_SEETAPS = 'RECEIVE_SEETAPS'

export const RECEIVE_RECMANUAL = 'RECEIVE_RECMANUAL'

export const RECEIVE_PULLREFRESH = 'RECEIVE_PULLREFRESH'

export const RECEIVE_HOTSEARCH = 'RECEIVE_HOTSEARCH'

export const RECEIVE_SEARCH_COMPLETE = 'RECEIVE_SEARCH_COMPLETE'

export const RECEIVE_SEETITLE = 'RECEIVE_SEETITLE'

export const RECEIVE_SEECOLLECTION = 'RECEIVE_SEECOLLECTION'

export const REVEIVE_BETTER_NEW = 'REVEIVE_BETTER_NEW'
